# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hobby', models.TextField()),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
